Update vitest.yml

diff --git a/.github/workflows/vitest.yml b/.github/workflows/vitest.yml
--- a/.github/workflows/vitest.yml
+++ b/.github/workflows/vitest.yml
@@ -1,30 +1,24 @@
 name: Vitest Tests on PR
-
 on:
   pull_request:
-    branches: [ main ]
-
+    branches: [ main, Development ]
 jobs:
   test:
     runs-on: ubuntu-latest
-
     steps:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
-
-    - name: Merge PR into develop
+    - name: Merge PR into main
       run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git checkout main
         git merge ${{ github.event.pull_request.head.sha }}
-
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '18'
-
     - name: Determine package manager and install dependencies
       run: |
         if [ -f "yarn.lock" ]; then
@@ -37,7 +31,6 @@ jobs:
           echo "No lockfile found, using npm install"
           npm install
         fi
-
     - name: Run Vitest tests
       run: |
         if [ -f "yarn.lock" ]; then
@@ -45,3 +38,16 @@ jobs:
         else
           npm run test
         fi
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Vitest Tests          # Name of the check run which will be created
+        path: reports/junit.xml     # Path to test results
+        reporter: jest-junit        # Format of test results
+    - name: Upload coverage report
+      uses: actions/upload-artifact@v3
+      if: always()
+      with:
+        name: coverage-report
+        path: coverage/
